export const PAGES = [
    {
        id: 0,
        story: "You wake up and find yourself in a jungle surrounded by three equally confused people. You see their names floating above their heads. You look up and see your own name, {player}. ",
        image: "/assets/images/jungle.jpg",
        button1: "Begin the adventure!",
        button2: " ",
    },
    {
        id: "river",
        story: "Yourself, and three companions, stubble upon a river. {randomCharacterName} approaches the river for a drink. As they reach the waters edge a giant hippo explodes from the water grabbing her in its mouth.",
        image: "/assets/images/river.jpg",
        button1: "Be a hero.",
        button2: "Run away.",
    },
    {
        id: "hippoDeath",
        story: "You are eaten by a hippo in an attempt to save them. GAME OVER.",
        image: "/assets/images/hippo.jpg",
        button1: " ",
        button2: " ",
    },
    {
        id: "car",
        story: "You run away from the hippos narrowly escaping their chomping jaws. As you flee a car pulls up alongside you. “Get in” the stranger shouts. You and the two remaining adventurers jump straight in.",
        image: "/assets/images/hippo.jpg",
        button1: "Introduce yourself.",
        button2: " ",
    },
    {
        id: "storyGoal",
        story: "Hello my name is {player}. The stranger greets you warmly. “My name is Nigel and you lucky adventurers have been chosen to lift the curse on Jumanji. You must take this jewel to the jaguar statue”. He hands you a jewel. “And here take this map, sorry its torn but maybe you can find the other part” he adds. You take the map. “Well this is your stop, good luck out there” Nigel says as he waves goodbye. You get out of the car and discuss what to do.",
        image: "/assets/images/jeep.jpg",
        button1: "This is too hard, lets just go home.",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    }
    
    


]