export const PAGE = [
    {
        id: "start",
        story: "You wake up and find yourself in a jungle surrounded by three equally confused people. You see their names floating above their heads. You look up and see your own name, {player}. ",
        image: " ",
        button1: "Begin the adventure!",
        button2: " ",
    },
    {
        id: "hippo",
        story: "Yourself, and three companions, stubble upon a river. {randomCharacterName} approaches the river for a drink. As they reach the waters edge a giant hippo explodes from the water grabbing her in its mouth.",
        image: " ",
        button1: "Be a hero.",
        button2: "Run away.",
    },
    {
        id: "hippoDeath",
        story: "You are eaten by a hippo in an attempt to save them. GAME OVER.",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    },
    {
        id: "",
        story: "",
        image: " ",
        button1: " ",
        button2: " ",
    }
    
    


]